version: "3.3"

services:
  mbaza-demo-stt:
    container_name: mbaza-demo-stt
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - mbaza-demo-stt
    ports:
      - "6910:6910"
    volumes:
      - ./sample_eng.txt:/code/demo_stt/sample_eng.txt
      - ./sample_kin.txt:/code/demo_stt/sample_kin.txt
    environment:
      - THREADS=2
      - PROCESSES=1
      - SRV_HOST=0.0.0.0
      - SRV_PORT=6910
      - APP_LOG_LEVEL=debug